### ISSUE TITLE
Compile doesn't work 

### ISSUE THREAD

**Issue by J05HI** [C-Higgins/Deezloader#7]

**Comment by C-Higgins** [comment]
It works for me. Be more specific; what is the error, what have you tried to fix it?

**Comment by J05HI** [comment]
Your command "./node_modules/.bin/electron ./" isn't working.
I'm on a windows machine.

**Comment by C-Higgins** [comment]
Yes, that is a bash command so it will not work on Windows. You want `node_modules\.bin\electron .\`

Note: this will start the app, but an exe will not be created. For that you will need to DIY and look into electron packaging modules. Originally the exe was distributed somewhere by the creator, but the resources were not included in the repo. If you don't want to type that command every time you could also look into just making a .bat to do it.

**Comment by J05HI** [comment]
@C-Higgins 
Oh okay, thanks for the answer :)
